# -*- coding: utf-8 -*-
"""AI Fire Detection System (FINAL).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11m6l8OaWvXmGe0UUcLEkHSsLwuS5dZRy

# 1. Install Dependencies
"""

!pip install ultralytics roboflow

from roboflow import Roboflow
from ultralytics import YOLO
import torch
import shutil
import os
import yaml

import matplotlib.pyplot as plt
import pandas as pd

from sklearn.model_selection import train_test_split

"""# 2. Download Dataset"""

rf = Roboflow(api_key="scjsFJgUQPnUaEAD11sa")
project = rf.workspace("fire-dataset-tp9jt").project("fire-detection-sejra")
version = project.version(1)
dataset = version.download("yolov8")

print(f"Dataset downloaded to: {dataset.location}")

"""# 3. Split Dataset"""

train_path = f"{dataset.location}/train"
valid_path = f"{dataset.location}/valid"

if os.path.exists(valid_path):
    shutil.rmtree(valid_path)

os.makedirs(f"{dataset.location}/valid/images", exist_ok=True)
os.makedirs(f"{dataset.location}/valid/labels", exist_ok=True)

# Filter gambar yang memiliki label
images = []
for f in os.listdir(f"{train_path}/images"):
    if f.endswith(('.jpg', '.png', '.jpeg')):
        label_file = f.replace('.jpg', '.txt').replace('.png', '.txt').replace('.jpeg', '.txt')
        if os.path.exists(f"{train_path}/labels/{label_file}"):
            images.append(f)

print(f"Total gambar valid: {len(images)}")

# Split 80% train, 20% valid
train_images, valid_images = train_test_split(images, test_size=0.2, random_state=42)

print(f"Train: {len(train_images)} gambar (80%)")
print(f"Valid: {len(valid_images)} gambar (20%)")

# Pindahkan ke valid
for img in valid_images:
    shutil.move(f"{train_path}/images/{img}", f"{dataset.location}/valid/images/{img}")
    label_file = img.replace('.jpg', '.txt').replace('.png', '.txt').replace('.jpeg', '.txt')
    if os.path.exists(f"{train_path}/labels/{label_file}"):
        shutil.move(f"{train_path}/labels/{label_file}", f"{dataset.location}/valid/labels/{label_file}")

# Update data.yaml
data_yaml_path = f"{dataset.location}/data.yaml"
with open(data_yaml_path, 'r') as f:
    data_config = yaml.safe_load(f)

data_config['val'] = '../valid/images'

with open(data_yaml_path, 'w') as f:
    yaml.dump(data_config, f)

print("✅ Split selesai!")

"""# 4. Distribusi Class"""

# Hitung distribusi di TRAIN SET
train_fire, train_smoke, train_unknown, train_boxes, train_files = count_classes_in_folder(train_labels_path)

# Hitung distribusi di VALID SET
valid_fire, valid_smoke, valid_unknown, valid_boxes, valid_files = count_classes_in_folder(valid_labels_path)

# Hitung distribusi TOTAL
total_fire = train_fire + valid_fire
total_smoke = train_smoke + valid_smoke
total_unknown = train_unknown + valid_unknown
total_boxes_all = train_boxes + valid_boxes
total_images = train_files + valid_files

# TAMPILKAN HASIL
print(f"\n📁 TRAIN SET:")
print(f"   - Jumlah gambar: {train_files}")
print(f"   - Total bounding box: {train_boxes}")
if train_boxes > 0:
    print(f"   - 🔥 FIRE (class 0): {train_fire} ({train_fire/train_boxes*100:.1f}%)")
    print(f"   - 💨 SMOKE (class 1): {train_smoke} ({train_smoke/train_boxes*100:.1f}%)")
    print(f"   - ❓ UNKNOWN (class 2): {train_unknown} ({train_unknown/train_boxes*100:.1f}%)")
else:
    print("   - Tidak ada bounding box")

print(f"\n📁 VALID SET:")
print(f"   - Jumlah gambar: {valid_files}")
print(f"   - Total bounding box: {valid_boxes}")
if valid_boxes > 0:
    print(f"   - 🔥 FIRE (class 0): {valid_fire} ({valid_fire/valid_boxes*100:.1f}%)")
    print(f"   - 💨 SMOKE (class 1): {valid_smoke} ({valid_smoke/valid_boxes*100:.1f}%)")
    print(f"   - ❓ UNKNOWN (class 2): {valid_unknown} ({valid_unknown/valid_boxes*100:.1f}%)")
else:
    print("   - Tidak ada bounding box")

print(f"\n📁 TOTAL (TRAIN + VALID):")
print(f"   - Total gambar: {total_images}")
print(f"   - Total bounding box: {total_boxes_all}")
if total_boxes_all > 0:
    print(f"   - 🔥 FIRE (class 0): {total_fire} ({total_fire/total_boxes_all*100:.1f}%)")
    print(f"   - 💨 SMOKE (class 1): {total_smoke} ({total_smoke/total_boxes_all*100:.1f}%)")
    print(f"   - ❓ UNKNOWN (class 2): {total_unknown} ({total_unknown/total_boxes_all*100:.1f}%)")

fig, axes = plt.subplots(1, 3, figsize=(16, 5))

# Warna untuk 3 class
colors = ['#FF4444', '#44FF44', '#FFA500']  # Merah, Hijau, Oranye
labels_class = ['🔥 FIRE', '💨 SMOKE', '❓ UNKNOWN']

# 1. Bar chart distribusi TRAIN SET
train_counts = [train_fire, train_smoke, train_unknown]
bars1 = axes[0].bar(labels_class, train_counts, color=colors, edgecolor='black')
axes[0].set_title('Distribusi Class di TRAIN SET', fontsize=12, fontweight='bold')
axes[0].set_ylabel('Jumlah Objek')
axes[0].set_xlabel('Kelas')
for bar, count in zip(bars1, train_counts):
    axes[0].text(bar.get_x() + bar.get_width()/2, bar.get_height() + 5,
                str(count), ha='center', fontweight='bold', fontsize=10)

# 2. Bar chart distribusi VALID SET
valid_counts = [valid_fire, valid_smoke, valid_unknown]
bars2 = axes[1].bar(labels_class, valid_counts, color=colors, edgecolor='black')
axes[1].set_title('Distribusi Class di VALID SET', fontsize=12, fontweight='bold')
axes[1].set_ylabel('Jumlah Objek')
axes[1].set_xlabel('Kelas')
for bar, count in zip(bars2, valid_counts):
    axes[1].text(bar.get_x() + bar.get_width()/2, bar.get_height() + 2,
                str(count), ha='center', fontweight='bold', fontsize=10)

# 3. Pie chart distribusi TOTAL
total_counts = [total_fire, total_smoke, total_unknown]
# Filter class yang jumlahnya > 0
non_zero_labels = [labels_class[i] for i in range(3) if total_counts[i] > 0]
non_zero_counts = [total_counts[i] for i in range(3) if total_counts[i] > 0]
non_zero_colors = [colors[i] for i in range(3) if total_counts[i] > 0]

explode = [0.05] * len(non_zero_labels)
axes[2].pie(non_zero_counts, explode=explode, labels=non_zero_labels,
            colors=non_zero_colors, autopct='%1.1f%%', shadow=True, startangle=90)
axes[2].set_title(f'Distribusi Total (TRAIN + VALID)\nTotal = {total_boxes_all} objek',
                  fontsize=12, fontweight='bold')
axes[2].axis('equal')

plt.tight_layout()
plt.savefig('class_distribution_3class.png', dpi=150, bbox_inches='tight')
plt.show()

#  ANALISIS UNKNOWN CLASS
print("\n" + "=" * 60)
print("🔍 ANALISIS UNKNOWN CLASS (Class 2)")
print("=" * 60)

if total_unknown > 0:
    unknown_percentage = (total_unknown / total_boxes_all) * 100
    print(f"Total objek UNKNOWN: {total_unknown} ({unknown_percentage:.1f}% dari total)")
    print(f"\n⚠️ Catatan: Class UNKNOWN biasanya mendeteksi:")
    print("   - Tulisan/papan reklame")
    print("   - Objek yang tidak relevan dengan api/asap")
    print("   - Labeling error dalam dataset")

    if unknown_percentage > 10:
        print(f"\n⚠️ PERINGATAN: UNKNOWN cukup besar ({unknown_percentage:.1f}%)!")
        print("   Ini dapat mempengaruhi performa deteksi api dan asap.")
        print("   Saran: Pertimbangkan untuk menghapus class UNKNOWN dari dataset.")
else:
    print("✅ Tidak ada objek UNKNOWN di dataset!")

print("\n" + "=" * 60)
print("⚖️ ANALISIS KESEIMBANGAN DATA (FIRE vs SMOKE)")
print("=" * 60)

total_fire_smoke = total_fire + total_smoke
if total_fire_smoke > 0:
    ratio_fire_smoke = total_fire / total_smoke if total_smoke > 0 else float('inf')
    print(f"🔥 FIRE: {total_fire} objek ({total_fire/total_fire_smoke*100:.1f}% dari Fire+Smoke)")
    print(f"💨 SMOKE: {total_smoke} objek ({total_smoke/total_fire_smoke*100:.1f}% dari Fire+Smoke)")
    print(f"\nRasio FIRE : SMOKE = 1 : {ratio_fire_smoke:.2f}")

    if 0.8 <= ratio_fire_smoke <= 1.2:
        print("✅ Dataset SEIMBANG (fire dan smoke hampir sama banyak)")
    elif ratio_fire_smoke > 1.2:
        print(f"⚠️ Dataset TIDAK SEIMBANG: Fire {ratio_fire_smoke:.1f}x lebih banyak dari Smoke")
    else:
        print(f"⚠️ Dataset TIDAK SEIMBANG: Smoke {1/ratio_fire_smoke:.1f}x lebih banyak dari Fire")
else:
    print("❌ Tidak ada objek Fire atau Smoke di dataset!")

# HAPUS CLASS UNKNOWN DARI LABEL
print("\n" + "=" * 60)
print("🗑️ MENGHAPUS CLASS UNKNOWN (CLASS 2) DARI LABEL")
print("=" * 60)

def remove_unknown_class_from_labels(labels_path):
    """
    Menghapus semua baris yang berisi class unknown (class_id = 2)
    dari file label .txt
    """
    if not os.path.exists(labels_path):
        print(f"⚠️ Folder tidak ditemukan: {labels_path}")
        return 0, 0

    label_files = [f for f in os.listdir(labels_path) if f.endswith('.txt')]
    total_removed = 0
    total_files_modified = 0

    for label_file in label_files:
        file_path = os.path.join(labels_path, label_file)

        # Baca semua baris
        with open(file_path, 'r') as f:
            lines = f.readlines()

        # Filter: hanya simpan baris dengan class 0 (fire) atau class 1 (smoke)
        filtered_lines = []
        removed_count = 0

        for line in lines:
            parts = line.strip().split()
            if len(parts) >= 1:
                class_id = int(parts[0])
                if class_id == 0 or class_id == 1:
                    filtered_lines.append(line)
                elif class_id == 2:
                    removed_count += 1

        # Jika ada yang dihapus, tulis ulang file
        if removed_count > 0:
            total_removed += removed_count
            total_files_modified += 1
            with open(file_path, 'w') as f:
                f.writelines(filtered_lines)

            # Jika file menjadi kosong, hapus file label (tidak perlu file kosong)
            if len(filtered_lines) == 0:
                os.remove(file_path)
                print(f"   🗑️ {label_file}: semua label dihapus (file dihapus)")
            else:
                print(f"   ✂️ {label_file}: dihapus {removed_count} unknown")

    return total_removed, total_files_modified

# Path ke folder label
train_labels_path = f"{dataset.location}/train/labels"
valid_labels_path = f"{dataset.location}/valid/labels"

# Hapus unknown dari TRAIN SET
print("\n📁 Memproses TRAIN SET...")
train_removed, train_modified = remove_unknown_class_from_labels(train_labels_path)

# Hapus unknown dari VALID SET
print("\n📁 Memproses VALID SET...")
valid_removed, valid_modified = remove_unknown_class_from_labels(valid_labels_path)

# Total
total_removed = train_removed + valid_removed
total_modified = train_modified + valid_modified

print("\n" + "=" * 60)
print("📊 RINGKASAN PENGHAPUSAN UNKNOWN")
print("=" * 60)
print(f"TRAIN SET: {train_removed} unknown dihapus dari {train_modified} file")
print(f"VALID SET: {valid_removed} unknown dihapus dari {valid_modified} file")
print(f"TOTAL: {total_removed} unknown dihapus dari {total_modified} file")

if total_removed == 0:
    print("\n✅ Tidak ada class unknown di dataset!")
else:
    print(f"\n✅ Berhasil menghapus {total_removed} objek unknown")
    print("   (Gambar tetap utuh, hanya label unknown yang dihapus)")

#  UPDATE data.yaml (nc=2, karena hanya fire & smoke)
print("\n" + "=" * 60)
print("📝 UPDATE data.yaml (nc=2 untuk Fire & Smoke saja)")
print("=" * 60)

data_yaml_path = f"{dataset.location}/data.yaml"

with open(data_yaml_path, 'r') as f:
    data_config = yaml.safe_load(f)

# Update jumlah class menjadi 2 (fire dan smoke)
data_config['nc'] = 2

# Update nama class (hapus unknown)
data_config['names'] = {0: 'fire', 1: 'smoke'}

with open(data_yaml_path, 'w') as f:
    yaml.dump(data_config, f)

print(f"✅ data.yaml diperbarui:")
print(f"   - nc: 2 (sebelumnya 3)")
print(f"   - names: {{0: 'fire', 1: 'smoke'}}")

#  VERIFIKASI SETELAH PENGHAPUSAN
print("\n" + "=" * 60)
print("🔍 VERIFIKASI SETELAH PENGHAPUSAN")
print("=" * 60)

def verify_no_unknown(labels_path, path_name):
    """Memastikan tidak ada lagi class unknown di file label"""
    if not os.path.exists(labels_path):
        print(f"⚠️ {path_name}: folder tidak ditemukan")
        return 0

    unknown_found = 0
    for label_file in os.listdir(labels_path):
        if label_file.endswith('.txt'):
            file_path = os.path.join(labels_path, label_file)
            with open(file_path, 'r') as f:
                for line in f:
                    parts = line.strip().split()
                    if len(parts) >= 1 and int(parts[0]) == 2:
                        unknown_found += 1
                        print(f"   ⚠️ Masih ada unknown di {label_file}")

    if unknown_found == 0:
        print(f"   ✅ {path_name}: tidak ada class unknown")
    else:
        print(f"   ❌ {path_name}: masih ada {unknown_found} unknown!")

    return unknown_found

# Verifikasi
verify_no_unknown(train_labels_path, "TRAIN SET")
verify_no_unknown(valid_labels_path, "VALID SET")

print("\n✅ SEMUA CLASS UNKNOWN BERHASIL DIHAPUS!")
print("   Dataset sekarang hanya berisi FIRE (class 0) dan SMOKE (class 1)")

"""# 5. Training Model YOLO"""

device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(f"Using device: {device}")

# Cek jumlah class di data.yaml sebelum training
data_yaml_path = f"{dataset.location}/data.yaml"
import yaml
with open(data_yaml_path, 'r') as f:
    data_config = yaml.safe_load(f)
print(f"📊 Dataset config: nc={data_config['nc']}, names={data_config['names']}")

# Load model YOLOv8n
model = YOLO("yolov8n.pt")

# Training
results = model.train(
    data=data_yaml_path,
    epochs=50,
    imgsz=512,
    batch=48,
    device=device,
    workers=8,
    half=True,
    patience=20,
    seed=42,
    save=True,
    save_period=10,
    val=True,
    project="fire_detection",
    name="exp_final_clean",
    exist_ok=True,
    pretrained=True,
    optimizer='AdamW',
    lr0=0.001,
    lrf=0.01,
    weight_decay=0.0005,
    warmup_epochs=3,
    cos_lr=True,
    cache=True,

    # Augmentasi
    degrees=5.0,
    translate=0.1,
    scale=0.5,
    fliplr=0.5,
    flipud=0.0,
    mosaic=1.0,
    mixup=0.1,
)

"""# 7. Visualisasi Hasil Evaluasi"""

val_results = model.val()
print(f"\n📈 HASIL VALIDASI:")
print(f"   mAP50: {val_results.box.map50:.4f}")
print(f"   mAP50-95: {val_results.box.map:.4f}")
print(f"   Precision: {val_results.box.mp:.4f}")
print(f"   Recall: {val_results.box.mr:.4f}")

import plotly.graph_objects as go
from plotly.subplots import make_subplots
import plotly.express as px
import pandas as pd
import os

# Path ke results.csv (sesuaikan dengan lokasi file kamu)
results_csv_path = "/content/results.csv"

# Cek apakah file ada
if os.path.exists(results_csv_path):
    df = pd.read_csv(results_csv_path)
    print(f"✅ Memuat {len(df)} epoch data dari {results_csv_path}")

    # Ambil nilai dari epoch terakhir (epoch 50) untuk validasi
    last_epoch = df.iloc[-1]

    # Hasil dari validation set (diambil dari kolom metrics/...)
    val_map50 = last_epoch['metrics/mAP50(B)']
    val_map50_95 = last_epoch['metrics/mAP50-95(B)']
    val_precision = last_epoch['metrics/precision(B)']
    val_recall = last_epoch['metrics/recall(B)']

    print(f"\n📊 HASIL VALIDASI (dari epoch terakhir):")
    print(f"   mAP50: {val_map50:.4f}")
    print(f"   mAP50-95: {val_map50_95:.4f}")
    print(f"   Precision: {val_precision:.4f}")
    print(f"   Recall: {val_recall:.4f}")

    print(f"\n📊 HASIL TEST SET (estimasi dari validation set):")
    print(f"   mAP50: {val_map50:.4f}")
    print(f"   mAP50-95: {val_map50_95:.4f}")
    print(f"   Precision: {val_precision:.4f}")
    print(f"   Recall: {val_recall:.4f}")
    print(f"\n⚠️ Catatan: results.csv hanya berisi data validation set.")
    print(f"   Untuk evaluasi test set yang akurat, load model best.pt dan jalankan model.val(split='test')")

    # ==================== VISUALISASI PLOTLY ====================

    # 1. BAR CHART: Perbandingan metrik
    fig1 = go.Figure()

    metrics = ['mAP50', 'mAP50-95', 'Precision', 'Recall']
    valid_scores = [val_map50, val_map50_95, val_precision, val_recall]

    fig1.add_trace(go.Bar(
        name='Validation Set',
        x=metrics,
        y=valid_scores,
        marker_color='#FF6B6B',
        text=[f'{x:.4f}' for x in valid_scores],
        textposition='auto'
    ))

    fig1.update_layout(
        title='Perbandingan Performa Model (Validation Set)',
        xaxis_title='Metrik',
        yaxis_title='Score',
        yaxis_range=[0, 1],
        template='plotly_white',
        height=500,
        font=dict(size=12)
    )

    fig1.show()

    # 2. GAUGE CHART untuk mAP50
    fig2 = go.Figure(go.Indicator(
        mode="gauge+number+delta",
        value=val_map50,
        title={'text': "Validation mAP50", 'font': {'size': 24}},
        delta={'reference': 0.5, 'increasing': {'color': "green"}},
        gauge={
            'axis': {'range': [0, 1], 'tickwidth': 1},
            'bar': {'color': "#FF6B6B"},
            'steps': [
                {'range': [0, 0.4], 'color': '#FFE5E5'},
                {'range': [0.4, 0.6], 'color': '#FFF3CD'},
                {'range': [0.6, 0.8], 'color': '#D4EDDA'},
                {'range': [0.8, 1], 'color': '#C3E6CB'}
            ],
            'threshold': {
                'line': {'color': "red", 'width': 4},
                'thickness': 0.75,
                'value': 0.5
            }
        }
    ))

    fig2.update_layout(title='🎯 mAP50 Model', height=450)
    fig2.show()

    # 3. LINE CHART: Training progress (mAP50 over epochs)
    fig3 = go.Figure()
    fig3.add_trace(go.Scatter(
        x=df['epoch'],
        y=df['metrics/mAP50(B)'],
        mode='lines+markers',
        name='mAP50',
        line=dict(color='red', width=2),
        marker=dict(size=4)
    ))
    fig3.update_layout(
        title='Training Progress: mAP50 vs Epoch',
        xaxis_title='Epoch',
        yaxis_title='mAP50',
        yaxis_range=[0, 0.6],
        template='plotly_white',
        height=450
    )
    fig3.show()

    # 4. LINE CHART: Loss over epochs
    fig4 = go.Figure()
    fig4.add_trace(go.Scatter(
        x=df['epoch'], y=df['train/box_loss'],
        mode='lines', name='Box Loss', line=dict(color='blue', width=2)
    ))
    fig4.add_trace(go.Scatter(
        x=df['epoch'], y=df['train/cls_loss'],
        mode='lines', name='Class Loss', line=dict(color='orange', width=2)
    ))
    fig4.update_layout(
        title='Training Loss',
        xaxis_title='Epoch',
        yaxis_title='Loss',
        template='plotly_white',
        height=450
    )
    fig4.show()

    # 5. TABEL RINGKASAN
    summary_data = {
        'Metrik': ['mAP50', 'mAP50-95', 'Precision', 'Recall'],
        'Nilai': [
            f'{val_map50:.4f}',
            f'{val_map50_95:.4f}',
            f'{val_precision:.4f}',
            f'{val_recall:.4f}'
        ]
    }
    df_summary = pd.DataFrame(summary_data)

    fig5 = go.Figure(data=[go.Table(
        header=dict(values=['<b>Metrik</b>', '<b>Nilai</b>'], fill_color='#2C3E50',
                    font=dict(color='white', size=12), align='center', height=40),
        cells=dict(values=[df_summary['Metrik'], df_summary['Nilai']],
                   fill_color='#FDFEFE', font=dict(color='#2C3E50', size=11), align='center', height=35)
    )])
    fig5.update_layout(title='📊 Ringkasan Performa Model', height=250)
    fig5.show()

else:
    print(f"❌ File tidak ditemukan: {results_csv_path}")
    print("   Coba cari dengan kode di bawah:")

    # Cari file results.csv
    import glob
    for f in glob.glob("/content/**/results.csv", recursive=True):
        print(f"   Ditemukan: {f}")

from ultralytics import YOLO

model = YOLO("/content/runs/detect/fire_detection/exp_final_clean/weights/best.pt")

results = model("fire test.jpg")

for r in results:
    print(r.boxes.conf)